<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\ServiceProvider;
use Illuminate\Database\Seeder;

class ServiceProviderSeeder extends Seeder
{
    public function run(): void
    {
        $cat = fn (string $name) => Category::where('name', $name)->value('id');

        $providers = [
            [
                'category_id'       => $cat('Restaurants & Cafes'),
                'name_en'           => "Casper & Gambini's",
                'name_ar'           => 'كاسبر وجامبيني',
                'short_description_en' => 'Casual contemporary dining with a wide menu.',
                'short_description_ar' => 'مطعم عصري بقائمة طعام واسعة.',
                'description_en'    => 'A favorite in October compounds, offering pastas, grills, sandwiches and desserts.',
                'description_ar'    => 'من المفضلات في كمبوندات أكتوبر، يقدم المعكرونة والمشاوي والساندويتشات والحلويات.',
                'phone'             => '+201001234567',
                'whatsapp'          => '+201001234567',
                'address_en'        => 'Mall, Janna October Compound',
                'address_ar'        => 'المول، كمبوند جنّة أكتوبر',
                'location_url'      => 'https://maps.google.com/?q=Janna+October',
                'working_hours_en'  => '10:00 AM - 1:00 AM',
                'working_hours_ar'  => 'من ١٠ صباحاً حتى ١ بعد منتصف الليل',
                'area_type'         => 'inside_compound',
                'is_featured'       => true,
            ],
            [
                'category_id'       => $cat('Restaurants & Cafes'),
                'name_en'           => 'Cilantro Cafe',
                'name_ar'           => 'سيلانترو كافيه',
                'short_description_en' => 'Coffee, light meals and workspace.',
                'short_description_ar' => 'قهوة ووجبات خفيفة ومساحة عمل.',
                'description_en'    => 'Specialty coffee, breakfast, sandwiches and pastries.',
                'description_ar'    => 'قهوة مختصة وإفطار وساندويتشات ومعجنات.',
                'phone'             => '+201112223344',
                'whatsapp'          => '+201112223344',
                'address_en'        => 'Commercial strip, Janna',
                'address_ar'        => 'المنطقة التجارية، جنّة',
                'working_hours_en'  => '8:00 AM - 12:00 AM',
                'working_hours_ar'  => 'من ٨ صباحاً حتى منتصف الليل',
                'area_type'         => 'inside_compound',
            ],
            [
                'category_id'       => $cat('Pharmacies'),
                'name_en'           => '19011 El-Ezaby Pharmacy',
                'name_ar'           => 'صيدلية العزبي ١٩٠١١',
                'short_description_en' => '24/7 pharmacy with delivery.',
                'short_description_ar' => 'صيدلية تعمل ٢٤ ساعة مع خدمة التوصيل.',
                'description_en'    => 'Hotline 19011. Open 24 hours, home delivery available.',
                'description_ar'    => 'خط ساخن ١٩٠١١. تعمل على مدار الساعة مع التوصيل للمنازل.',
                'phone'             => '19011',
                'whatsapp'          => '+201019011000',
                'address_en'        => 'Near Janna gate 2',
                'address_ar'        => 'بالقرب من بوابة جنّة رقم ٢',
                'working_hours_en'  => 'Open 24 hours',
                'working_hours_ar'  => 'مفتوح ٢٤ ساعة',
                'area_type'         => 'near_compound',
                'is_featured'       => true,
            ],
            [
                'category_id'       => $cat('Pharmacies'),
                'name_en'           => 'Seif Pharmacy',
                'name_ar'           => 'صيدلية سيف',
                'short_description_en' => 'Trusted local pharmacy.',
                'short_description_ar' => 'صيدلية محلية موثوقة.',
                'description_en'    => 'Wide range of medications and supplements.',
                'description_ar'    => 'مجموعة واسعة من الأدوية والمكملات الغذائية.',
                'phone'             => '19199',
                'whatsapp'          => '+201019199000',
                'address_en'        => '6th of October City',
                'address_ar'        => 'مدينة ٦ أكتوبر',
                'working_hours_en'  => '9:00 AM - 2:00 AM',
                'working_hours_ar'  => 'من ٩ صباحاً حتى ٢ صباحاً',
                'area_type'         => 'near_compound',
            ],
            [
                'category_id'       => $cat('Clinics'),
                'name_en'           => 'Family Medical Clinic',
                'name_ar'           => 'عيادة طب الأسرة',
                'short_description_en' => 'General practice and pediatrics.',
                'short_description_ar' => 'طب عام وأطفال.',
                'description_en'    => 'Family doctors, vaccinations, pediatric care.',
                'description_ar'    => 'أطباء أسرة وتطعيمات ورعاية أطفال.',
                'phone'             => '+20223456789',
                'whatsapp'          => '+201005556677',
                'address_en'        => 'Medical block, Janna',
                'address_ar'        => 'المجمع الطبي، جنّة',
                'working_hours_en'  => '9:00 AM - 9:00 PM',
                'working_hours_ar'  => 'من ٩ صباحاً حتى ٩ مساءً',
                'area_type'         => 'inside_compound',
            ],
            [
                'category_id'       => $cat('Maintenance'),
                'name_en'           => 'Janna Maintenance Team',
                'name_ar'           => 'فريق صيانة جنّة',
                'short_description_en' => 'Plumbing, electricity, AC and handyman services.',
                'short_description_ar' => 'سباكة وكهرباء وتكييف وأعمال صيانة عامة.',
                'description_en'    => 'Compound-affiliated maintenance with same-day visits.',
                'description_ar'    => 'فريق صيانة تابع للكمبوند مع زيارات في نفس اليوم.',
                'phone'             => '+201500001111',
                'whatsapp'          => '+201500001111',
                'address_en'        => 'Compound office',
                'address_ar'        => 'مكتب الكمبوند',
                'working_hours_en'  => '8:00 AM - 8:00 PM',
                'working_hours_ar'  => 'من ٨ صباحاً حتى ٨ مساءً',
                'area_type'         => 'inside_compound',
                'is_featured'       => true,
            ],
            [
                'category_id'       => $cat('Supermarkets'),
                'name_en'           => 'Carrefour Market',
                'name_ar'           => 'كارفور ماركت',
                'short_description_en' => 'Daily groceries and fresh produce.',
                'short_description_ar' => 'بقالة يومية ومنتجات طازجة.',
                'description_en'    => 'Carrefour Market branch with delivery.',
                'description_ar'    => 'فرع كارفور ماركت مع خدمة التوصيل.',
                'phone'             => '19306',
                'whatsapp'          => '+201019306000',
                'address_en'        => 'Near Mall of Arabia',
                'address_ar'        => 'بالقرب من مول العرب',
                'working_hours_en'  => '8:00 AM - 1:00 AM',
                'working_hours_ar'  => 'من ٨ صباحاً حتى ١ صباحاً',
                'area_type'         => 'near_compound',
            ],
            [
                'category_id'       => $cat('Cleaning Services'),
                'name_en'           => 'CleanHome October',
                'name_ar'           => 'كلين هوم أكتوبر',
                'short_description_en' => 'Apartment & villa cleaning, deep cleaning.',
                'short_description_ar' => 'تنظيف شقق وفيلات وتنظيف عميق.',
                'description_en'    => 'Trained team, eco-friendly products, hourly or full-day bookings (off-app).',
                'description_ar'    => 'فريق مدرّب ومنتجات صديقة للبيئة وحجوزات بالساعة أو لليوم كامل (خارج التطبيق).',
                'phone'             => '+201207778899',
                'whatsapp'          => '+201207778899',
                'address_en'        => '6th of October',
                'address_ar'        => '٦ أكتوبر',
                'working_hours_en'  => '9:00 AM - 7:00 PM',
                'working_hours_ar'  => 'من ٩ صباحاً حتى ٧ مساءً',
                'area_type'         => 'near_compound',
            ],
            [
                'category_id'       => $cat('Compound Services'),
                'name_en'           => 'Compound Security Office',
                'name_ar'           => 'مكتب أمن الكمبوند',
                'short_description_en' => 'Gate access, lost & found, incidents.',
                'short_description_ar' => 'الدخول من البوابات والمفقودات والحوادث.',
                'description_en'    => 'Reachable 24/7 from any gate or by phone.',
                'description_ar'    => 'يمكن الوصول إليه على مدار الساعة من أي بوابة أو عبر الهاتف.',
                'phone'             => '+20238001000',
                'address_en'        => 'Main gate, Janna',
                'address_ar'        => 'البوابة الرئيسية، جنّة',
                'working_hours_en'  => 'Open 24 hours',
                'working_hours_ar'  => 'مفتوح ٢٤ ساعة',
                'area_type'         => 'inside_compound',
            ],
            [
                'category_id'       => $cat('Compound Services'),
                'name_en'           => 'Pool & Landscaping',
                'name_ar'           => 'المسبح والمناظر الطبيعية',
                'short_description_en' => 'Pool maintenance and garden care.',
                'short_description_ar' => 'صيانة المسبح والعناية بالحدائق.',
                'description_en'    => 'Managed by the compound facilities team.',
                'description_ar'    => 'يدار بواسطة فريق مرافق الكمبوند.',
                'phone'             => '+20238001001',
                'address_en'        => 'Facilities block',
                'address_ar'        => 'مبنى المرافق',
                'working_hours_en'  => '8:00 AM - 6:00 PM',
                'working_hours_ar'  => 'من ٨ صباحاً حتى ٦ مساءً',
                'area_type'         => 'inside_compound',
            ],
        ];

        foreach ($providers as $i => $row) {
            ServiceProvider::updateOrCreate(
                ['name' => $row['name_en']],
                array_merge($row, [
                    // Mirror *_en into legacy single-language columns to keep
                    // the schema's NOT NULL `name` happy.
                    'name'              => $row['name_en'],
                    'description'       => $row['description_en'],
                    'short_description' => $row['short_description_en'],
                    'address'           => $row['address_en'],
                    'working_hours'     => $row['working_hours_en'],
                    'sort_order'        => $i + 1,
                    'is_active'         => true,
                ]),
            );
        }
    }
}
